Display and lock
allexks/smart-locc pull request #3
Opened 2021-04-29 05:34 UTC by zotakk4o

2021-04-29 09:26 UTC, allexks requested changes

2021-04-29 09:26 UTC, allexks commented on Lock.hpp
> +		void lock();
I think in this PR we should also call these classes and methods inside the `.ino` file

2021-04-29 09:26 UTC, allexks commented on DisplayConfig.hpp
> +		static void displayDoorUnlockedMessage(Display& display);
What if we instead have this repeating `Display&` parameter as a member of the class instead and have all these methods be non-static?
Also please remove `StateManager::getStateMessage` as it won't be needed and use this `DisplayConfig` in the `.ino` file to setup the display accordingly

2021-05-01 07:23 UTC, ihristova11 commented on DisplayConfig.hpp
> +#define DISPLAYCONFIG_HPP
Maybe `__DISPLAY_CONFIG__HPP__` will be better, just for consistency :)

2021-05-01 07:23 UTC, ihristova11 commented on Lock.hpp
> +#define LOCK_HPP
`__LOCK__HPP__`, just for consistency :)

2021-05-01 07:23 UTC, ihristova11 commented on Display.hpp
> +#define DISPLAY_HPP
`__DISPLAY_HPP__`, just for consistency :)

2021-05-25 16:35 UTC, merged